[package]
name = "indxvec"
version = "0.1.4"
authors = ["Libor Spacek"]
edition = "2018"
description = "Efficiently sorting, merging, ranking, searching and reversing generic vectors"
readme = "README.md"
homepage = "https://github.com/liborty/indxvec"
repository = "https://github.com/liborty/indxvec"
license = "Apache-2.0"
keywords = ["merge-sort","ranking","merge","binary-search","generic-vectors"]
categories = ["science","mathematics","algorithms","data-structures","rust-patterns"]
include = [
    "src/*.rs",
    "tests/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
# anyhow = "^1"
