[package]
name = "indxvec"
version = "0.2.10"
authors = ["Libor Spacek"]
edition = "2021"
description = "Sets implemented as generic vectors. Efficiently sorting, merging, ranking, searching, reversing, intersecting, etc."
readme = "README.md"
homepage = "https://github.com/liborty/indxvec"
repository = "https://github.com/liborty/indxvec"
license = "Apache-2.0"
keywords = ["ordered-sets","merge-sort","set-operations","ranking-searching","generic-vectors"]
categories = ["mathematics","algorithms","data-structures","rust-patterns","simulation"]
include = [
    "src/*.rs",
    "tests/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]
[badges]
maintenance = { status = "actively-developed" }
[lib]
[dependencies]
# anyhow = "^1"
